// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzhe8f_bW-8BlAyK9BbA6fzbdh1GeKzq0',
    appId: '1:425878695800:web:d4b4e49af776752922a28d',
    messagingSenderId: '425878695800',
    projectId: 'healthy-in',
    authDomain: 'healthy-in.firebaseapp.com',
    storageBucket: 'healthy-in.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB12yeVlSF86cI3qoaarVqyW15TMeTCsRU',
    appId: '1:425878695800:android:13586e01a347aa6122a28d',
    messagingSenderId: '425878695800',
    projectId: 'healthy-in',
    storageBucket: 'healthy-in.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfnz-zTKs0hYibvxDUeVqsOZLuDrn_VjE',
    appId: '1:425878695800:ios:064d77d768480d7222a28d',
    messagingSenderId: '425878695800',
    projectId: 'healthy-in',
    storageBucket: 'healthy-in.appspot.com',
    iosClientId: '425878695800-21ns0cuom3qunpi4hcseka77k61tsa2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthyIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfnz-zTKs0hYibvxDUeVqsOZLuDrn_VjE',
    appId: '1:425878695800:ios:064d77d768480d7222a28d',
    messagingSenderId: '425878695800',
    projectId: 'healthy-in',
    storageBucket: 'healthy-in.appspot.com',
    iosClientId: '425878695800-21ns0cuom3qunpi4hcseka77k61tsa2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthyIn',
  );
}
